# Generated by Django 4.2 on 2023-05-01 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('univeristy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('image', models.ImageField(null=True, upload_to='image')),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='univeristy.category')),
            ],
        ),
        migrations.DeleteModel(
            name='ProgramLanguagse',
        ),
    ]
