# Generated by Django 4.2 on 2023-05-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univeristy', '0002_category_subcategory_delete_programlanguagse'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
