# Generated by Django 4.2 on 2023-05-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('univeristy', '0003_subcategory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='logo',
            field=models.ImageField(null=True, upload_to='image'),
        ),
    ]
